### PR TITLE
Hold Space to activate Hint-mode

### PR DESCRIPTION
**Pull request by dexterleng**
some unorganized notes:

- space key down, shift space key up
- all key ups are passed through -> the assumption here is that key ups don't do anything, so we don't handle them to reduce complexity

```
// r key down -> pass through
onEvent() called. state=nothing keyDown=true characters=Optional("r") modifiers=NSEventModifierFlags(rawValue: 256) isARepeat=false
transformed event. state=nothing keyDown=true characters=Optional("r") modifiers=NSEventModifierFlags(rawValue: 256) isARepeat=false

// space key down -> set timeout
onEvent() called. state=nothing keyDown=true characters=Optional(" ") modifiers=NSEventModifierFlags(rawValue: 256) isARepeat=false
setAwaitingKey() called
onEvent transformed to nil

// r key up -> suppressed
// should we pass through, or avoid setting time out if still waiting for key up?
onEvent() called. state=awaitingDelay keyDown=false characters=Optional("r") modifiers=NSEventModifierFlags(rawValue: 256) isARepeat=false
onEvent transformed to nil
```

### CODE REVIEW

**Comment by dexterleng** [comment]
@blackketter @colossatr0n Would you mind giving this a try? I noticed one user mapped a thumb key to Hint-mode, and I thought I'd implement something like to that for users with standard keyboards. I've tried it out for a day and I really like it! I've ironed out bugs from the previous hold key code. I would love to hear your thoughts.

Oh, and key sequence activation isn't broken in this one.

[Vimac-Hold-Key.zip](https://github.com/dexterleng/vimac/files/6364086/Vimac-Hold-Key.zip)

**Comment by blackketter** [comment]
> @blackketter @colossatr0n Would you mind giving this a try? I noticed one user mapped a thumb key to Hint-mode, and I thought I'd implement something like to that for users with standard keyboards. I've tried it out for a day and I really like it! I've ironed out bugs from the previous hold key code. I would love to hear your thoughts.

I like this better than holding F.  It definitely feels a little slower than a ctrl-F or sequence trigger, so I'm not sure I'd personally switch but it feels like a good solution for new users.

Downside:  Many people hold down the space bar to add spaces via key repeat.   Maybe not your target market, but it's something to think about.

**Comment by blackketter** [comment]
I hate to ask for more preferences, but this _is_ a power user app.  I suspect that letting the user select the hold key and adjust the hold-down timing threshold would be useful.

**Comment by dexterleng** [comment]
> I hate to ask for more preferences, but this is a power user app. I suspect that letting the user select the hold key and adjust the hold-down timing threshold would be useful.

I agree that this is important. I'm would like to validate that this something that users would like to use first before adding more configuration options.

**Comment by dexterleng** [comment]
> Downside: Many people hold down the space bar to add spaces via key repeat. Maybe not your target market, but it's something to think about.

Right, Photoshop requires hold Space for some tasks. The ability to configuring hold key will fix it, but until users try it out I don't know if this is a good activation method worth spending more time on.

**Comment by colossatr0n** [comment]
Right off the bat I like this better than using f. Another option would be to hold the semi-colon/colon key to activate hint mode. It's on the home row and it's not likely someone would need to hold the semicolon/colon key in a regular workflow like they would the spacebar as blackketter pointed out.

**Comment by kiding** [comment]
I simply love this. Great job!

**Pull request merged**
